#define SIZEOF_task_struct 0x12c0
#define task_struct_thread_info_OFF                   0x000
#define task_struct___state_OFF                       0x020
#define task_struct_stack_OFF                         0x028
#define task_struct_usage_OFF                         0x030
#define task_struct_flags_OFF                         0x034
#define task_struct_ptrace_OFF                        0x038
#define task_struct_on_cpu_OFF                        0x03c
#define task_struct_prio_OFF                          0x074
#define task_struct_static_prio_OFF                   0x078
#define task_struct_normal_prio_OFF                   0x07c
#define task_struct_rt_priority_OFF                   0x080
#define task_struct_se_OFF                            0x0c0
#define task_struct_rt_OFF                            0x200
#define task_struct_dl_OFF                            0x250
#define task_struct_sched_class_OFF                   0x340
#define task_struct_sched_task_group_OFF              0x348
#define task_struct_stats_OFF                         0x380
#define task_struct_policy_OFF                        0x488
#define task_struct_cpus_mask_OFF                     0x4a0
#define task_struct_nr_cpus_allowed_OFF               0x48c
#define task_struct_sched_info_OFF                    0x530
#define task_struct_tasks_OFF                         0x550
#define task_struct_pushable_tasks_OFF                0x560
#define task_struct_mm_OFF                            0x5a0
#define task_struct_active_mm_OFF                     0x5a8
#define task_struct_exit_state_OFF                    0x5c4
#define task_struct_exit_code_OFF                     0x5c8
#define task_struct_exit_signal_OFF                   0x5cc
#define task_struct_pdeath_signal_OFF                 0x5d0
#define task_struct_jobctl_OFF                        0x5d8
#define task_struct_personality_OFF                   0x5e0
#define task_struct_atomic_flags_OFF                  0x5f0
#define task_struct_pid_OFF                           0x630
#define task_struct_tgid_OFF                          0x634
#define task_struct_real_parent_OFF                   0x640
#define task_struct_parent_OFF                        0x648
#define task_struct_children_OFF                      0x650
#define task_struct_sibling_OFF                       0x660
#define task_struct_group_leader_OFF                  0x670
#define task_struct_comm_OFF                          0x848
#define task_struct_real_cred_OFF                     0x830
#define task_struct_cred_OFF                          0x838
#define task_struct_seccomp_OFF                       0x900
#define task_struct_pi_lock_OFF                       0x924
#define task_struct_pi_waiters_OFF                    0x938
#define task_struct_pi_top_task_OFF                   0x948
#define task_struct_pi_blocked_on_OFF                 0x950

#define SIZEOF_cred 0xb0
#define cred_usage_OFF                                0x000
#define cred_uid_OFF                                  0x004
#define cred_gid_OFF                                  0x008
#define cred_suid_OFF                                 0x00c
#define cred_sgid_OFF                                 0x010
#define cred_euid_OFF                                 0x014
#define cred_egid_OFF                                 0x018
#define cred_fsuid_OFF                                0x01c
#define cred_fsgid_OFF                                0x020
#define cred_securebits_OFF                           0x024
#define cred_cap_inheritable_OFF                      0x028
#define cred_cap_permitted_OFF                        0x030
#define cred_cap_effective_OFF                        0x038
#define cred_cap_bset_OFF                             0x040
#define cred_cap_ambient_OFF                          0x048
#define cred_user_OFF                                 0x080
#define cred_user_ns_OFF                              0x088
#define cred_group_info_OFF                           0x098
#define cred_rcu_OFF                                  0x0a0
#define cred_security_OFF                             0x078

#define SIZEOF_rt_mutex_waiter 0x58
#define rt_mutex_waiter_tree_entry_OFF                0x000
#define rt_mutex_waiter_pi_tree_entry_OFF             0x018
#define rt_mutex_waiter_task_OFF                      0x030
#define rt_mutex_waiter_lock_OFF                      0x038
#define rt_mutex_waiter_wake_state_OFF                0x040
#define rt_mutex_waiter_prio_OFF                      0x044
#define rt_mutex_waiter_deadline_OFF                  0x048
#define rt_mutex_waiter_ww_ctx_OFF                    0x050

#define SIZEOF_file_operations 0x110
#define file_operations_owner_OFF                     0x000
#define file_operations_llseek_OFF                    0x008
#define file_operations_read_OFF                      0x010
#define file_operations_write_OFF                     0x018
#define file_operations_read_iter_OFF                 0x020
#define file_operations_write_iter_OFF                0x028
#define file_operations_iopoll_OFF                    0x030
#define file_operations_iterate_OFF                   0x038
#define file_operations_iterate_shared_OFF            0x040
#define file_operations_poll_OFF                      0x048
#define file_operations_unlocked_ioctl_OFF            0x050
#define file_operations_compat_ioctl_OFF              0x058
#define file_operations_mmap_OFF                      0x060
#define file_operations_open_OFF                      0x070
#define file_operations_flush_OFF                     0x078
#define file_operations_release_OFF                   0x080
#define file_operations_fsync_OFF                     0x088
#define file_operations_fasync_OFF                    0x090
#define file_operations_lock_OFF                      0x098
#define file_operations_get_unmapped_area_OFF         0x0a8
#define file_operations_check_flags_OFF               0x0b0
#define file_operations_splice_read_OFF               0x0c8
#define file_operations_splice_write_OFF              0x0c0
#define file_operations_setlease_OFF                  0x0d0
#define file_operations_show_fdinfo_OFF               0x0e0

#define SIZEOF_ctl_table 0x40
#define ctl_table_procname_OFF                        0x000
#define ctl_table_data_OFF                            0x008
#define ctl_table_maxlen_OFF                          0x010
#define ctl_table_mode_OFF                            0x014
#define ctl_table_child_OFF                           0x018
#define ctl_table_proc_handler_OFF                    0x020
#define ctl_table_extra1_OFF                          0x030
#define ctl_table_extra2_OFF                          0x038

#define SIZEOF_seccomp 0x10
#define seccomp_mode_OFF                              0x000
#define seccomp_filter_OFF                            0x008

#define SIZEOF_file 0x108
#define file_f_op_OFF                                 0x028
#define file_private_data_OFF                         0x0d8
#define file_f_inode_OFF                              0x020
#define file_f_cred_OFF                               0x0a0

#define SIZEOF_struct vm_operations_struct 0x90
#define open_OFF                                      0x000
#define close_OFF                                     0x008
#define fault_OFF                                     0x028
#define page_mkwrite_OFF                              0x048
#define access_OFF                                    0x058
#define name_OFF                                      0x060
#define mremap_OFF                                    0x018
